# -*- coding: utf-8 -*-
"""UCL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABYm2X_zF7YE_upgxkACGS1Xxkl3d94r
"""

# This is data from the UEFA Champions League season 2021-22

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

defending = '/content/drive/MyDrive/UCL/defending.csv'
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(pd.read_csv(defending))

#I added a column "Expected Goals" to allow for better analyses
goals = pd.read_csv('/content/drive/MyDrive/UCL/goals.csv')
display(goals)

club_total_goals = goals.groupby('club')['goals'].sum().sort_values(ascending=False)
display(club_total_goals)

"""This shows that the Best Attacking Team is FC Bayern Munchen"""

goalkeeping = '/content/drive/MyDrive/UCL/goalkeeping.csv'
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
goalkeeping = pd.read_csv(goalkeeping)
display(goalkeeping)

club_total_conceded_goals = goalkeeping.groupby('club')['conceded'].sum().sort_values(ascending=True)
display(club_total_conceded_goals)

"""This shows that the Best Defensive Team is Sevilla"""

matches_played = goalkeeping.groupby('club')['match_played'].sum().sort_values(ascending=False)
display(matches_played)

goal_differential = club_total_goals - club_total_conceded_goals

data = {
    'Club Goals': club_total_goals,
    'Conceded Goals': club_total_conceded_goals,
    'Goals Per Game': club_total_goals/matches_played,
    'Matches Played': matches_played,
    'Goal Differential': goal_differential,
    'Goal Differential Per Game': goal_differential/matches_played
}
matches_played['Man. City'] = 12
df = pd.DataFrame(data)
display(df.sort_values(by='Goal Differential', ascending=False))

plt.figure(figsize=(12, 6))
sorted_df = df.sort_values(by='Goal Differential Per Game', ascending=False)
ax = sns.barplot(x=sorted_df.index, y='Goal Differential Per Game', data=sorted_df, order=sorted_df.index)


plt.plot(sorted_df.index, sorted_df['Goal Differential Per Game'], color='red', marker='o')

plt.xticks(rotation=90)
plt.title('Goal Differential Per Game by Clubs in UCL 2021-22')
plt.xlabel('Club')
plt.ylabel('Goal Differential Per Game')
plt.tight_layout()



plt.show()

goal_dif_performance = np.linspace(min(df['Goal Differential Per Game']), max(df['Goal Differential Per Game']), 5)
group_names = ["Poor", "Average", "Good", "Excellent"]
df['Goal Differential Performance'] = pd.cut(df['Goal Differential Per Game'], bins = goal_dif_performance, labels=group_names, include_lowest=True)
display(df.sort_values(by=['Matches Played'], ascending=[False]))

"""While luck might influence match outcomes, we can make a strong prediction that the teams that either had "good" or "excellent" performances progressed to the latter stages of the tournament

But this data is a little decieveing. If I were not a follower of football, I would have thought that Bayern reached the Finals, but that was not the case. In fact, Liverpool and Real Madrid were the finalists.
"""

display(df.sort_values(by=['Goal Differential Performance', 'Goal Differential Per Game' ], ascending=[False, False]))

"""Now for some others stats"""

passing = '/content/drive/MyDrive/UCL/distribution.csv'
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
passing = pd.read_csv(passing)
display(passing)

passes_completed = passing.groupby('club')['pass_completed'].sum().sort_values(ascending=False)
display(passes_completed)

data2 = {
    'Club Passes': passes_completed,
    'Matches Played': matches_played,
    'Passes Per Game': passes_completed/matches_played
}
df2 = pd.DataFrame(data2)
display(df2.sort_values(by=['Passes Per Game'], ascending=[False]))

team_playstyle = np.linspace(min(df2['Passes Per Game']), max(df2['Passes Per Game']), 5)
team_playstyles = ['Low Pass Volume', 'Moderate Pass Volume', 'High Pass Volume ', 'Very High Pass Volume']
df2['Team Playstyle'] = pd.cut(df2['Passes Per Game'], bins = team_playstyle, labels=team_playstyles, include_lowest=True)
display(df2.sort_values(by=['Passes Per Game'], ascending=[False]))

"""Using this, we might guess the team's playstyle type. If you are new to football, you can search up different playstyles and make assumptions.

I have created bins with 4 categories to assist you
"""

display(df2.sort_values(by=['Matches Played'], ascending=[False]))

#I am scraping data from transfermarkt with help from gemini
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.transfermarkt.co.uk/uefa-champions-league/teilnehmer/pokalwettbewerb/CL/saison_id/2021"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, "html.parser")
table = soup.find("table", {"class": "items"})
rows = table.find_all("tr")

# Extract team name, total market value, and average market value per player
team_data = []
for row in rows[1:]:  # Skip the header row
    cols = row.find_all("td")
    if len(cols) > 5:  # Ensure there are enough columns
        # The team name is in the second column (index 1) within an 'a' tag
        team_tag = cols[1].find('a')
        team_name = team_tag.text.strip() if team_tag else "N/A" # Use "N/A" if the tag is not found
        # The 'Total Market Value' is in the fifth column (index 4)
        total_market_value = cols[4].text.strip()
        # The 'Avg. market value per player' is in the sixth column (index 5)
        avg_market_value = cols[5].text.strip()
        team_data.append({'Club': team_name, 'Market Value': total_market_value, 'ø Market Value': avg_market_value})

# Create a pandas DataFrame
market_value_df = pd.DataFrame(team_data)

# Display the DataFrame
display(market_value_df)

# I am merging df and df2 to the market value table (gemini helped a bit with the cleaning and merging)
merged_df = df.merge(df2, left_index=True, right_index=True)

market_value_df['Club'] = market_value_df['Club'].str.replace(' FC', '').str.replace(' CF', '').str.replace(' KV', '').str.replace(' JK', '').str.replace(' BC', '').str.replace(' SK', '').str.replace(' SV', '').str.replace(' FK', '').str.replace(' FF', '').str.replace(' FK', '').str.replace(' KV', '').str.replace(' FC', '').str.replace(' CF', '').str.replace(' KV', '').str.replace(' JK', '').str.replace(' BC', '').str.replace(' SK', '').str.replace(' SV', '').str.replace(' FK', '').str.replace(' FF', '').str.replace(' FK', '').str.replace(' KV', '').str.replace(' BSC ', '').str.replace('AFC ', '').str.replace('PSV ', '').str.replace('BVB ', '').str.replace('TSG ', '').str.replace('US ', '').str.replace('SSC ', '').str.replace('PFC ', '')


market_value_df['Club'] = market_value_df['Club'].replace({
    'Real Madrid': 'Real Madrid',
    'Manchester City': 'Man. City',
    'Chelsea': 'Chelsea',
    'Liverpool': 'Liverpool',
    'Paris Saint-Germain': 'Paris',
    'Barcelona': 'Barcelona',
    'Bayern Munich': 'Bayern',
    'Manchester United': 'Man. United',
    'Inter Milan': 'Inter Milan',
    'Juventus': 'Juventus',
    'Atlético de Madrid': 'Atlético',
    'RB Leipzig': 'Leipzig',
    'AC Milan': 'AC Milan',
    'Sporting CP': 'Sporting CP',
    'Atalanta': 'Atalanta',
    'Borussia Dortmund': 'Dortmund',
    'Porto': 'Porto',
    'SL Benfica': 'Benfica',
    'VfL Wolfsburg': 'Wolfsburg',
    'LOSC Lille': 'LOSC',
    'Ajax Amsterdam': 'Ajax',
    'Villarreal': 'Villarreal',
    'Zenit St. Petersburg': 'Zenit',
    'Club Brugge': 'Club Brugge',
    'Besiktas': 'Beşiktaş',
    'Shakhtar Donetsk': 'Shakhtar Donetsk',
    'Sevilla': 'Sevilla',
    'Red Bull Salzburg': 'Salzburg',
    'Dynamo Kyiv': 'Dynamo Kyiv',
    'Young Boys': 'Young Boys',
    'Malmö': 'Malmö',
    'Sheriff Tiraspol': 'Sheriff'
})


merged_df = merged_df.merge(market_value_df, left_index=True, right_on='Club')

merged_df = merged_df.reset_index(drop=True)

merged_df = merged_df.rename(columns={'Matches Played_y': 'Matches Played'})
merged_df = merged_df.drop(columns=['Matches Played_x'])


cols = merged_df.columns.tolist()
cols.insert(0, cols.pop(cols.index('Club')))
merged_df = merged_df[cols]

display(merged_df)

"""There is a clear correlation between "ø Market Value" (Market Value per Player) and team performance (Goal Dif Performance and Pass Volume). But this does not imply causation.  """



#I am scraping data from transfermarkt with help from gemini
import pandas as pd
import os


directory_path = '/content/drive/MyDrive/UCL/Matches' # Replace with the actual path to your files


all_files = os.listdir(directory_path)


csv_files = [os.path.join(directory_path, f) for f in all_files if f.endswith('.csv')]


dataframe_list = []


for csv_file in csv_files:
    try:
        df = pd.read_csv(csv_file)
        dataframe_list.append(df)
    except Exception as e:
        print(f"Error reading {csv_file}: {e}")


combined_df = pd.concat(dataframe_list, ignore_index=True)


display(combined_df.sort_values(by='Match Number', ascending=True))


print(f"\nTotal number of rows in the combined dataframe: {len(combined_df)}")

# Drop duplicate rows based on key match identifying columns
combined_df = combined_df.drop_duplicates(subset=['Match Number', 'Round Number', 'Date', 'Home Team', 'Away Team'])

# Display the first few rows of the dataframe after dropping duplicates
display(combined_df.sort_values(by = 'Match Number', ascending = True).head())

# Display the total number of rows in the dataframe after dropping duplicates
print(f"\nTotal number of rows in the dataframe after dropping duplicates: {len(combined_df)}")

# Identify duplicate rows based on the subset of key columns
duplicate_rows = combined_df[combined_df.duplicated(subset=['Match Number', 'Round Number', 'Date', 'Home Team', 'Away Team'], keep=False)]

# Sort the duplicate rows to see them grouped together
duplicate_rows_sorted = duplicate_rows.sort_values(by=['Match Number', 'Round Number', 'Date', 'Home Team', 'Away Team'])

# Display the duplicate rows
display(duplicate_rows_sorted)

print(f"\nNumber of rows identified as duplicates: {len(duplicate_rows)}")

#I reset the unnmaed column to the left
display(combined_df.sort_values(by='Match Number', ascending=True))

display(combined_df.dtypes)
combined_df['Date'] = pd.to_datetime(combined_df['Date'])
combined_df.describe()

missing_values = combined_df.isnull().sum()

display(missing_values)

combined_df[['Home Score', 'Away Score']] = combined_df['Result'].str.split(' - ', expand=True).astype(int)

combined_df['home win'] = (combined_df['Home Score'] > combined_df['Away Score']).astype(int)

combined_df['away win'] = (combined_df['Away Score'] > combined_df['Home Score']).astype(int)

display(combined_df.sort_values(by='Match Number', ascending=True))

counts = [combined_df['home win'].value_counts(), combined_df['away win'].value_counts()]
labels = ['Home Win', 'Away Win', 'Draw']

# Extract the win counts from the value_counts() Series
home_wins = counts[0].get(1, 0) # Get count for home win (value 1), default to 0 if no wins
away_wins = counts[1].get(1, 0) # Get count for away win (value 1), default to 0 if no wins
draws = len(combined_df) - home_wins - away_wins # Calculate draws

win_counts = [home_wins, away_wins, draws]

plt.figure(figsize=(10, 6))
ax = plt.bar(labels, win_counts)
plt.ylabel("Count")
plt.title("Match Outcomes: Home Win, Away Win, and Draw")

# Add the value of the counts at the top of the bars
for bar in ax:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, round(yval), ha='center', va='bottom')

plt.show()

"""The actual number of matches that were played in the UCL 2021/2022 were 125, but the sum is 189. I tried dropping duplicates, but was unable to do so, this is due to the way in which the data was stored. As the files were team-wise records, the same match may have been displayed twice. But not all mathes had 2 entries, hence the odd numbers as values.

Thus, we will be assuming 189 matches were played.

It is clear that teams playing at their home venue had a "home advantage". Away teams have a good amount of wins, too.
"""

from scipy import stats

pearson_coef = stats.pearsonr(combined_df['Home Score'], combined_df['home win'])
print("Pearson Correlation Coefficient:", pearson_coef[0])

combined_df['Goal Difference'] = combined_df['Home Score'] - combined_df['Away Score']


correlation_home_win = combined_df['Goal Difference'].corr(combined_df['home win'])


correlation_away_win = combined_df['Goal Difference'].corr(combined_df['away win'])

print(f"Pearson Correlation Coefficient between Goal Difference and Home Win: {correlation_home_win}")
print(f"Pearson Correlation Coefficient between Goal Difference and Away Win: {correlation_away_win}")

def convert_market_value(value):
    value = value.replace('€', '').strip()
    if 'bn' in value:
        return float(value.replace('bn', '')) * 1000
    elif 'm' in value:
        return float(value.replace('m', ''))
    elif 'k' in value:
        return float(value.replace('k', '')) / 1000
    return 0.0 # Return 0 for any unexpected values


market_value_df['Market Value_numeric'] = market_value_df['Market Value'].apply(convert_market_value)


combined_df = combined_df.merge(market_value_df[['Club', 'Market Value_numeric']],
                                left_on='Home Team',
                                right_on='Club',
                                how='left',
                                suffixes=('', '_home'))


combined_df = combined_df.rename(columns={'Market Value_numeric': 'Home Team Market Value'})


combined_df = combined_df.drop('Club', axis=1)


combined_df = combined_df.merge(market_value_df[['Club', 'Market Value_numeric']],
                                left_on='Away Team',
                                right_on='Club',
                                how='left',
                                suffixes=('', '_away'))


combined_df = combined_df.rename(columns={'Market Value_numeric': 'Away Team Market Value'})


combined_df = combined_df.drop('Club', axis=1)



combined_df['Market Value Difference'] = combined_df['Home Team Market Value'] - combined_df['Away Team Market Value']


display(combined_df.head())

combined_df_clubs = pd.concat([combined_df['Home Team'], combined_df['Away Team']]).unique()


market_value_clubs = market_value_df['Club'].unique()


unmatched_clubs = [club for club in combined_df_clubs if club not in market_value_clubs]


print("Club names in combined_df that do not have a match in market_value_df:")
display(unmatched_clubs)

club_name_mapping = {
    'Besiktas JK': 'Besiktas',
    'BSC Young Boys': 'Young Boys',
    'AC Milan': 'Milan',
    'FC Porto': 'Porto',
    'FC Barcelona': 'Barcelona',
    'Inter Milan': 'Inter',
    'FC Sheriff Tiraspol': 'Sheriff'
}


market_value_df['Club'] = market_value_df['Club'].replace(club_name_mapping)


existing_market_value_cols = ['Home Team Market Value', 'Away Team Market Value', 'Market Value Difference']
combined_df = combined_df.drop(columns=[col for col in existing_market_value_cols if col in combined_df.columns])


def convert_market_value(value):
    value = value.replace('€', '').strip()
    if 'bn' in value:
        return float(value.replace('bn', '')) * 1000
    elif 'm' in value:
        return float(value.replace('m', ''))
    elif 'k' in value:
        return float(value.replace('k', '')) / 1000
    return 0.0 # Return 0 for any unexpected values


market_value_df['Market Value_numeric'] = market_value_df['Market Value'].apply(convert_market_value)

combined_df = combined_df.merge(market_value_df[['Club', 'Market Value_numeric']],
                                left_on='Home Team',
                                right_on='Club',
                                how='left',
                                suffixes=('', '_home'))


combined_df = combined_df.rename(columns={'Market Value_numeric': 'Home Team Market Value'})


combined_df = combined_df.drop('Club', axis=1)



combined_df = combined_df.merge(market_value_df[['Club', 'Market Value_numeric']],
                                left_on='Away Team',
                                right_on='Club',
                                how='left',
                                suffixes=('', '_away'))


combined_df = combined_df.rename(columns={'Market Value_numeric': 'Away Team Market Value'})


combined_df = combined_df.drop('Club', axis=1)



combined_df['Market Value Difference'] = combined_df['Home Team Market Value'] - combined_df['Away Team Market Value']



display(combined_df.head())


print("\nMissing values after standardization and re-merge:")
display(combined_df[['Home Team Market Value', 'Away Team Market Value', 'Market Value Difference']].isnull().sum())

# I dropped rows where 'Market Value Difference' is missing
combined_df = combined_df.dropna(subset=['Market Value Difference'])


print(f"Number of rows after dropping missing market value differences: {len(combined_df)}")

display(combined_df.head())

# Calculate the Pearson correlation coefficient between 'Market Value Difference' and 'home win'
correlation_market_value_home_win = combined_df['Market Value Difference'].corr(combined_df['home win'])

print(f"Pearson Correlation Coefficient between Market Value Difference and Home Win: {correlation_market_value_home_win}")

"""These two variables do not have that strong a correlation. It isn't negligible either. I will proceed by looking at the different correlation values."""